#!/usr/bin/env bash
#
# Copyright (c) 2015, Joyent, Inc. All rights reserved.
#
# Void specific setup
# 
#  Configure resolv.conf  if not set
if [ ! -e /etc/resolv.conf ]; then
  echo "# AUTOMATIC ZONE CONFIG" > /etc/resolv.conf
  for i in $(mdata-get sdc:resolvers | jq -r .[]); do
    echo nameserver $i >> /etc/resolv.conf
  done
fi
# load common functions and vars
. /lib/smartdc/common.lib

